title: Apollo Docs
propertytitle: Add GraphQL to your stack and start building apps faster.
subtitle: Apollo Docs
description: A guide to using the Apollo platform.
versions:
  - '1'
sidebar_categories:
  Fundamentals:
    - fundamentals/platform
    - fundamentals/benefits
    - fundamentals/tips
  Guides:
    - guides/schema-design
    - guides/versioning
    - guides/security
    - guides/access-control
    - guides/monitoring
github_repo: apollographql/apollo
content_root: docs/source

url: https://www.apollographql.com/docs
root: /docs/

public_dir: public/docs
