title: Developers
propertytitle: Add GraphQL to your stack and start building apps faster.
subtitle:
description: A guide to using the Apollo platform.
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Fundamentals:
    - fundamentals/platform
    - fundamentals/benefits
    - fundamentals/tips
  Guides:
    - guides/schema-design
    - guides/versioning
    - guides/security
    - guides/access-control
    - guides/monitoring
    - guides/state-mgmt
  Platform:
    - platform/client
    - platform/server
    - platform/engine
github_repo: apollographql/apollo
content_root: docs/source

url: https://www.apollographql.com/docs
root: /docs/

public_dir: public/docs
